### ISSUE TITLE
Discussion point

### ISSUE THREAD

**Issue by TheBeardedLlama** [AndyBeverlySchool/MongoDb.Bson.NodaTime#1]
Hey @tetious, I was looking for Mongo serializers for NodaTime and came across your project.

It should do for now, but I was wondering if you might be open to suggestions/contributions?

**Comment by tetious** [comment]
Glad you found it useful, and yep, contributions are welcome.

**Comment by TheBeardedLlama** [comment]
Excellent!
So what do you think of the following?
- Follow the current noda development more closely (v1 and v2)
- Follow the pattern Jon Skeet has applied for the JsonNet serialisation more closely

I'd be happy to elaborate if something doesn't make sense :)

**Comment by tetious** [comment]
For the first item, v2 support would be welcome.

I'll definitely need more details as to what you intend on the second item. :)

**Comment by TheBeardedLlama** [comment]
No worries, I wouldn't just go off and do stuff&copy; :)

What I have in mind for the second one is to align what you've done with the way Mr Skeet has done the jsonnet converters. The purpose for this would be so people know what to expect.

You've pretty much done most of it I believe from the brief look I had at the source (perhaps you looked at those before you did your package).

In addition following the pattern more closely would mean renaming to `NodaTime.Serialization.MongoDb` , but I would understand if you'd rather not do that (although it's early enough to not affect too many people) :)

(We can/should split these up into proper&copy; tasks so it's not one big massive commit)

**Comment by tetious** [comment]
I selected the current name to reflect the opposite perspective, in that it is serialization for Mongo, rather than serialization for NodaTime. Does that make sense? Given this, I think I'd prefer keeping the current name. 

I think I did use the JsonNet implementation as a guide. My memory is terrible. If you see opportunities to clean things up, by all means go for it.

**Comment by TheBeardedLlama** [comment]
I'm not sure if it does make sense to me. The serialization support for Json.Net is in `NodaTime.Serialization.JsonNet` and for ServiceStack in `NodaTime.Serialization.ServiceStackText`. Both are serialization helpers for those frameworks, similar to what you referred to as serialization for MongoDb. I'm not sure I see the difference. I'm not saying I need to, just that I'm unable  :)

Ok no worries. I'll just be aligning, so the changes shouldn't be groundbreaking.

I suppose it's pertinent to ask what your plan was for this package moving forward? Was it a one off for a project you did at work? Did you plan to keep at it? etc.

**Comment by tetious** [comment]
Yeah, that's a fair point. You can look at it from either direction, I guess. ;)

As far as future plans, I built this to fill a need, and it is complete enough for us, so feature-wise I've nothing planned. I do intend to update it to .net core RTM at some point soon, once the mongo guys release driver version 2.3 and I'm able to work through some problems with the .net cli on my dev machine. (I run Arch Linux, which is about as far from a golden path for the .net guys as possible. :D)

Support for NodaTime 2.0 was also in the back of my mind, probably as part of the larger migration to .net core.

**Comment by TheBeardedLlama** [comment]
Exactly; that's why I was talking about "following Noda's pattern".

Ok I'm just wondering now if I should step off your toes and do a separate package... hmmmm

**Comment by tetious** [comment]
Your call, but I don't feel like you're stepping on my toes. I don't want to discourage you from contributing, and this is a specialized enough project that it seems wasteful to me to have two implementations. 

What if we renamed it as part of adding nodatime 2 support, but kept the old name for 1.x? Upgrading a project to NodaTime 2 would likely involve other code changes anyway, as part a major version update, so it would possibly annoy folks less.

I've found that name changes in package management systems are frustrating to communicate, as there is no clean or obvious mechanism for doing so. We have a couple hundred users presently, if the nuget package download stats are to be believed. I think it is important to carefully consider the impact/confusion renaming would have.

Doing this as part of a major version upgrade would help there, I think. Your thoughts?

**Comment by TheBeardedLlama** [comment]
Yes, I was thinking that as well. It would be rather pointless to have two packages that do the same thing pretty much.

Sorry, I didn't mean to imply that the reason was the name. I was just talking it over. I'm not that fussed to be honest :)

So shall you/I add an item to "add Noda 2 support" or would you rather make the issue tracking more granular?

**Comment by TheBeardedLlama** [comment]
Everything ok?

**Comment by tetious** [comment]
Sorry, I thought I replied to this. One tracker for Noda 2 is fine by me.

**Comment by TheBeardedLlama** [comment]
Cool, I'll start looking at this soon (I hope :smiley:)
