### ISSUE TITLE
Add support for NodaTime 2

### ISSUE THREAD

**Issue by TheBeardedLlama** [AndyBeverlySchool/MongoDb.Bson.NodaTime#2]
Issue to track adding support for NodaTime 2

**Comment by BoasE** [comment]
same here.  the support for NodaTime2 is essential as only NodaTime2 runs on .net core

**Comment by tetious** [comment]
You can use NodaTime 1.4 with .net core, as with any project targeting PCL. In fact, we wrote this for a .net core project, and use it that way exclusively. :) We also have a .netstandard1.5 package out on nuget.

You'll need to import the PCL target, like this:

```
    "netstandard1.5": { 
      "imports": "portable-net40+sl5+win8+wp8+wpa81" 
    },
```

And you'll need to add Microsoft.NETCore.Portable.Compatibility. If you install MongoDb.Bson.NodaTime, this may happen automatically, though I'm not certain of that.

2.0 support will happen, but I've no idea when. PRs are welcome!

**Comment by TheBeardedLlama** [comment]
sorry, I've dropped the ball on this one big time!

I will see what I can do in the next couple of weeks

**Comment by johnknoop** [comment]
Any progress on this? Let me know if you want a pull request.

**Comment by tetious** [comment]
PRs are absolutely welcome! :)

**Comment by johnknoop** [comment]
Created a PR just now

**Comment by tetious** [comment]
Pushed to Nuget as v2.0.0. Many thanks @johnknoop!
