### ISSUE TITLE
filter using inequality?

### ISSUE THREAD

**Issue by SurajGupta** [AndyBeverlySchool/MongoDb.Bson.NodaTime#4]
Does this serializer support inequality filters on fields of type `LocalDate`, `LocalTime`, and `LocalDateTime`?  Is that something you've tested?  I performed a quick test and found that `LocalDate` converts to a Mongo string.  Are you relying on Mongo string comparison for this?  Have the serializer been constructed in such a way that strings are formatted so that, when all possible dates/times/datetimes are sorted, that they are in order from earliest to latest date/time/datetime?  Am I thinking about this issue incorrectly?

**Comment by SurajGupta** [comment]
Also, while serializing to string is more readable, it should make any filter much slower than if ints or longs were used.  Was that a deliberate choice?

**Comment by tetious** [comment]
The serializations are using NodaTime's "default" ISO representations intended for this purpose, and are ISO-8601 compliant. As such, they should sort properly. If you've found a problem with this, an example failing test would be appreciated.

Sticking with the ISO date representations was a deliberate choice.

**Comment by SurajGupta** [comment]
thank you for the quick response!
