### ISSUE TITLE
1.2.0 does not support .NET Framework 4.6.1

### ISSUE THREAD

**Issue by davenewza** [AndyBeverlySchool/MongoDb.Bson.NodaTime#5]
MongoDb.Bson.NodaTime 1.1.0 supports .NET 4.6.1 just fine, but 1.2.0 does not. Could we target this framework as well?

**Comment by tetious** [comment]
Sorry about that. I'll have 1.2.1 out shortly to fix this.

**Comment by tetious** [comment]
This should be resolved with the 1.2.1 release on NuGet.
