### ISSUE TITLE
Request: Implement serializer for ZonedDateTime

### ISSUE THREAD

**Issue by johnknoop** [AndyBeverlySchool/MongoDb.Bson.NodaTime#7]
If you want, you can reuse the code I posted in this SO thread:

https://stackoverflow.com/questions/17882795/nodatime-with-mongodb-value-class-nodatime-zoneddatetime-cannot-be-deserialized/44960803#44960803

I'm using it myself and it works like a charm.

**Comment by tetious** [comment]
This should be straightforward. I'll see if I can implement this today.

**Comment by tetious** [comment]
Implemented in v1.3.0. Should be on Nuget shortly.

**Comment by johnknoop** [comment]
That was fast :-)
