### ISSUE TITLE
BclDateTimeZone Timezone doesn't Deserialize

### ISSUE THREAD

**Issue by kabua** [AndyBeverlySchool/MongoDb.Bson.NodaTime#9]
Hey, getting my feet wet in Mongo and thought I would see how well it serialized and deserialized NodaTime v1.3.2, which it didn't then I found your package (v1.3.0) and was able to serialize a ZonedDateTime but couldn't deserialize it.

I got this exception
``
The specified time zone identifier is not recognized. Value being parsed: '2008-07-08T05:30:00 ^Central Standard Time (-05)'. (^ indicates error position.)
``

Here's the code:

```
static void Main(string[] args)
{
    try
    {
        NodaTimeSerializers.Register();

        var client = new MongoClient();
        var database = client.GetDatabase("Test");

        var person = new Person
        {
            Name = "A",
            BirthDay = new ZonedDateTime(new LocalDateTime(2008, 7, 8, 5, 30), BclDateTimeZone.ForSystemDefault(), Offset.FromHours(-5))
        };

        var persons = database.GetCollection<Person>("Person");
        persons.InsertOne(person);

        var p = persons.AsQueryable().First();
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        throw;
    }

    Console.WriteLine("Done.");
    Console.ReadKey();
}
```

Looks like the deserializer isn't checking for Bcl based time zone information.

**Comment by tetious** [comment]
I don't have time to investigate this more closely at the moment, but I suspect this will never work reliably because NodaTime can't always map the System.TimeZoneInfo back to a NodaTime DateTimeZone.

Does it work if you call `DateTimeZoneProviders.Tzdb.GetSystemDefault()`? I think it might.

**Comment by tetious** [comment]
Please reopen if you are still having issues.
